### ISSUE TITLE
[docs] correct enumeration of "key contracts"

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0-ethereum#108]
the enumeration of key contracts in the [contracts readme](https://github.com/risc0/risc0-ethereum/tree/main/contracts#key-contracts) is self-contradictory -- it says "the 2 key contracts you'll need [as a user]..." and then goes on to enumerate 4 contracts (only some of which you need to think about as a user)

<img width="869" alt="image" src="https://github.com/risc0/risc0-ethereum/assets/15272444/58a0eae4-e082-4366-9b7e-d1a035e55138">

**Comment by pdg744** [comment]
My instinct is that the right approach here is to have the top-of-page focus on what users need to think about and move the implementation details to a separate section.

**Comment by nategraf** [comment]
I've done some work to fix the most immediate issue (saying their are two items in a list of four) and to improve the organization and clarity. It's still centered on the contracts, enumerating each and their purpose, because I expect that folks coming to this document are looking to read the implementations.

https://github.com/risc0/risc0-ethereum/pull/149
