### ISSUE TITLE
[BUG] Why drop relay from risc0-ethereum

### ISSUE THREAD

**Issue by hunshenshi** [risc0/risc0-ethereum#148]
## Bug Report

Why drop relay from risc0-ethereum #122 , and now where is the relay? I need use tokenize_snark_receipt this func. Thanks

## Steps to Reproduce

1.
2.
3.

## Your Environment

- risc0-ethereum version:
- Rust version:
- Platform/OS:

**Comment by nategraf** [comment]
Hey @hunshenshi, thanks for asking and I can definitely provide some more context.

We deprecated and now deleted it because it ended up being kind of clunky, having been based on some assumptions that turned out to be incorrect / became outdated.

When it was created, one assumptions is that requests would come from on-chain contract calls. This is appealing because it means the app dev can interact with the prover entirely on-chain. It is severely limiting because it means all inputs must be available on-chain, either in state or in calldata. This is a problem for gas-optimizing use cases because posting the data is usually the most expensive part of a transaction. It is also limiting for privacy use cases, because there is no way to provide provide inputs. We updated it to add a REST API to address this, but it removes our main benefit of keeping things on-chain, because now the client has code that interacts with the relay via a REST API. Another issue that comes up is that it a "bad kind of magic". The relay is actually solving a pretty simple problem, but it ends up adding complexity while by hiding things from the developer.

The publisher is designed to be an example app, to show devs how they might integrate this functionality with their clients (e.g. dApp front-ends) or servers. It is intended that developers use it as a starting point, but mostly discard it as they integrate more tightly with their existing application. The point of about the relayers adding complexity can be seen by the fact that they publisher app is ~150 lines or code, including the CLI arg definitions. The relay in total was much more than this.

Another important development released with zkVM 1.0 and the new Foundry template is that the `risc_zkvm::Prover` type can be used for producing fake proofs, local proofs, and proofs via Bonsai. With that, most devs shouldn't need to use the `bonsai-sdk` directly, which removes a lot of the complexity the relay was trying to address (e.g. by providing a mock bonsai API).

There is still a lot of work to do here. For one, we want to work toward a "no host code" model. With the zkVM, you need a "host" to run the guest, feeding it inputs, receiving outputs, etc. Right now, we don't have a standardized guest interface, and so each host is guest-specific. We want to provide a standardized host that can run any guest that implements a general interface. With that, we can ship a CLI tool with cargo risczero that could replace the need for devs to maintain their own host code, which is one of the main functions of the publisher app. We also need things like a TypeScript SDK and a Go SDK to aid in integration with clients and servers implemented in those languages.

As we keep working on these things, we are hoping we can provide a really seamless and easy to integrate developer experience and we decided the relay wasn't going to work well in the model we are heading towards.
