### ISSUE TITLE
Solidity compilation can sometimes fail with error about `isDevMode()`

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-ethereum#26]

**Comment by Cardosaum** [comment]
This issue can happen in the definition of `devMode` ([source file](https://github.com/risc0/risc0-ethereum/blob/90d08442ac83170e94f7670e924bab27cefc6141/contracts/src/RiscZeroCheats.sol#L33-L38))

The current function signature is `function devMode() internal view returns (bool)`, a `view` function.
The problem arises by the fact that `forge` fails to compile the function complaining that this function can not be `view`, but we didn't see this compilation error in CI and it doesn't seem clear why this function should not be `view`.

It's not clear if the problem is a compiler version mismatch or something else.

**Comment by capossele** [comment]
Fixed by #37
