### ISSUE TITLE
Refactor Solidity types in view call library to be defined in `.sol` files instead of using the `sol!` macro

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-ethereum#70]
One rough edge in the view call library is that the `BlockCommitment` type is defined only in the Rust source code through a `sol!` macro. As a result, it is difficult to use in Solidity smart contracts to build upon it. Moving `BlockCommitment` and any other Solidity types into contracts that can be imported into smart contract projects would improve the developer experience.

**Comment by Wollac** [comment]
To give some context, this is the use case we want to address:

It's about the `BlockCommitment` structure ([defined here](https://github.com/risc0/risc0-ethereum/blob/main/view-call/src/lib.rs#L90-L96))
The guest is committing to a block commitment (obviously) as well as other journal data. So they have defined their own (solidity) struct that contains a block commitment + his other data.
The trouble, of course, is that `BlockCommitment` is defined within a `sol! { ... }` block. So when they went to define their own output struct (again in a `sol! { ... }`) macro, with a field of type `BlockCommitment`, the (sol) macro complained that it couldn't find the (solidity) definition of `BlockCommitment`.

**Comment by Wollac** [comment]
### Problem description
The function `block_commitment()` returns the following Solidity struct:
```solidity
struct BlockCommitment {
    bytes32 blockHash;
    uint blockNumber;
}
 ```
 Calling `.abi_encode()` returns the bytes that can then be used to verify the commitment on-chain.
 
 However, when more data is committed to the journal, it gets more complicated. When the output is defined in the following way:
  ```rust
sol! {
    struct BlockCommitment {
        bytes32 blockHash;
        uint256 blockNumber;
    }

    struct Journal {
        BlockCommitment commitment;
        bytes data;
    }
}
 ```
 The `BlockCommitment` is a different rust-type and cannot be assigned.

⚠️ Even putting `BlockCommitment` inside a `.sol` file does not fix this issue. 

### Solution

Instead of redefining the `BlockCommitment`, the existing type should be reused.
```rust
use risc0_steel::BlockCommitment;

sol! {
    struct Journal {
        BlockCommitment commitment;
        bytes data;
    }
}
```

### Open questions:
- How are we going to showcase this design?
- We could still put the `BlockCommitment` into an interface `sol` file. Would that simplify the usage in Solidity?
